version: '3'
services:
  web:
    build: .
    command: sh /mymess/scripts/startup.sh
    volumes:
      - .:/mymess
    ports:
      - "3000:3000"
    container_name: mymess
    links:
      - db
      - redis
    stdin_open: true
    tty: true
  db:
    image: postgres
    container_name: db

  redis:
    image: redis
    container_name: redis

